local MessageProvider = {}

function binarize(tensor) -- Input Generated by randn
	return (torch.ge(tensor, 0.5)):float() -- :mul(2):add(-1)
end

function MessageProvider:configure(batchSize, msgLength, fixMessage)
	self.batchSize = batchSize
	self.msgLength = msgLength
	self.deterministicMessage = binarize(torch.rand(1, msgLength):repeatTensor(batchSize, 1))
	if fixMessage then
		print("Message is fixed")
	    self.fixMessage = true
	end
end

function MessageProvider:generate()
	if self.fixMessage then
		return self.deterministicMessage
	end
	return binarize(torch.rand(self.batchSize, self.msgLength))
end

return MessageProvider